{ ... }:
{
  # Placeholder hardware configuration for cubesat.
  # Replace with the real file generated by `nixos-generate-config` on the VPS.
  # This stub exists so the flake evaluates and CI can run.
  boot.initrd.availableKernelModules = [ ];
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS";
    fsType = "ext4";
  };
  swapDevices = [ ];
}
